Repository blockscout/blockscout-rs, pull requests merged in 2025-03, with the labels that each got.

#1267 feat(multi): multichain service optimizations
  .gitignore
  multichain-aggregator/Cargo.lock
  multichain-aggregator/Cargo.toml
  multichain-aggregator/multichain-aggregator-logic/src/repository/addresses.rs
  multichain-aggregator/multichain-aggregator-logic/src/repository/block_ranges.rs
  multichain-aggregator/multichain-aggregator-logic/src/repository/chains.rs
  multichain-aggregator/multichain-aggregator-logic/src/repository/hashes.rs
  multichain-aggregator/multichain-aggregator-logic/src/services/search.rs
  multichain-aggregator/multichain-aggregator-logic/src/types/addresses.rs
  multichain-aggregator/multichain-aggregator-logic/src/types/hashes.rs
  multichain-aggregator/multichain-aggregator-proto/build.rs
  multichain-aggregator/multichain-aggregator-server/src/server.rs
  multichain-aggregator/multichain-aggregator-server/src/services/mod.rs
  multichain-aggregator/multichain-aggregator-server/src/services/multichain_aggregator.rs
  multichain-aggregator/multichain-aggregator-server/src/services/repo.rs
  multichain-aggregator/multichain-aggregator-server/src/settings.rs
Labels: feat

#1129 fix(launcher): more controlled shutdown
  libs/blockscout-service-launcher/Cargo.toml
  libs/blockscout-service-launcher/src/launcher/launch.rs
  libs/blockscout-service-launcher/src/launcher/metrics.rs
  libs/blockscout-service-launcher/src/launcher/mod.rs
  libs/blockscout-service-launcher/src/launcher/shutdown.rs
Labels: fix

#1289 Update badges in readme
  README.md
Labels: feat

#1276 feat(verifier): implement verifier-alliance based verification approach
  smart-contract-verifier/Cargo.lock
  smart-contract-verifier/Cargo.toml
  smart-contract-verifier/smart-contract-verifier-proto/src/lib.rs
  smart-contract-verifier/smart-contract-verifier-server/src/services/solidity_verifier.rs
  smart-contract-verifier/smart-contract-verifier-server/src/types/mod.rs
  smart-contract-verifier/smart-contract-verifier-server/src/types/solidity_multi_part.rs
  smart-contract-verifier/smart-contract-verifier-server/src/types/solidity_standard_json.rs
  smart-contract-verifier/smart-contract-verifier-server/src/types/verification_result.rs
  smart-contract-verifier/smart-contract-verifier-server/tests/solidity.rs
  smart-contract-verifier/smart-contract-verifier-server/tests/solidity_multiple.rs
  smart-contract-verifier/smart-contract-verifier-server/tests/standard_json.rs
  smart-contract-verifier/smart-contract-verifier-server/tests/test_cases_solidity/libraries_manually_linked.json
  smart-contract-verifier/smart-contract-verifier/Cargo.toml
  smart-contract-verifier/smart-contract-verifier/src/common_types.rs
  smart-contract-verifier/smart-contract-verifier/src/compiler/compilers.rs
  smart-contract-verifier/smart-contract-verifier/src/lib.rs
  smart-contract-verifier/smart-contract-verifier/src/solidity/client.rs
  smart-contract-verifier/smart-contract-verifier/src/solidity/mod.rs
  smart-contract-verifier/smart-contract-verifier/src/solidity/multi_part.rs
  smart-contract-verifier/smart-contract-verifier/src/solidity/standard_json.rs
  smart-contract-verifier/smart-contract-verifier/src/solidity/types.rs
  smart-contract-verifier/smart-contract-verifier/src/verifier/new_verifier.rs
  smart-contract-verifier/smart-contract-verifier/src/verify_new/cbor_auxdata.rs
  smart-contract-verifier/smart-contract-verifier/src/verify_new/compilation.rs
  smart-contract-verifier/smart-contract-verifier/src/verify_new/compiler_output.rs
  smart-contract-verifier/smart-contract-verifier/src/verify_new/evm_compilers.rs
  smart-contract-verifier/smart-contract-verifier/src/verify_new/mod.rs
  smart-contract-verifier/smart-contract-verifier/src/verify_new/solc_compiler.rs
  smart-contract-verifier/smart-contract-verifier/src/verify_new/verification.rs
  smart-contract-verifier/smart-contract-verifier/src/verify_new/verifier.rs
Labels: feat

#1292 feat(stats): chart update requests - validate input instead of silent error
  stats/stats-server/src/read_service.rs
  stats/stats-server/tests/it/mock_blockscout_reindex.rs
  stats/stats-server/tests/it/mock_blockscout_simple/stats_not_indexed.rs
Labels: feat

#1298 fix(stats): do not show waiting charts + test
  stats/stats-server/src/read_service.rs
  stats/stats-server/src/runtime_setup.rs
  stats/stats-server/src/update_service.rs
  stats/stats-server/src/update_tracker.rs
  stats/stats-server/tests/it/mock_blockscout_simple/common_tests.rs
Labels: bug
